version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
      next-typescript-eslint:
        patterns:
          - "next"
          - "eslint"
          - "eslint-config-next"
          - "typescript"
          - "typescript-eslint"
          - "@typescript-eslint/*"
      everything-else:
        patterns:
          - "*"
        exclude-patterns:
          - "react"
          - "react-*"
          - "next"
          - "eslint"
          - "eslint-config-next"
          - "typescript"
          - "typescript-eslint"
          - "@typescript-eslint/*"
